/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SalesKey = IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Nat });
export const Category = IDL.Record({
  'achieved' : IDL.Nat,
  'target' : IDL.Nat,
});
export const SalesData = IDL.Record({
  'plan' : Category,
  'withoutCoin' : Category,
  'overallSale' : Category,
  'studded' : Category,
  'plain' : Category,
});

export const idlService = IDL.Service({
  'getAllMonths' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(SalesKey, SalesData))],
      ['query'],
    ),
  'getAllMonthsSorted' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(SalesKey, SalesData))],
      ['query'],
    ),
  'getMonth' : IDL.Func([SalesKey], [SalesData], ['query']),
  'saveMonth' : IDL.Func([SalesKey, SalesData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SalesKey = IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Nat });
  const Category = IDL.Record({ 'achieved' : IDL.Nat, 'target' : IDL.Nat });
  const SalesData = IDL.Record({
    'plan' : Category,
    'withoutCoin' : Category,
    'overallSale' : Category,
    'studded' : Category,
    'plain' : Category,
  });
  
  return IDL.Service({
    'getAllMonths' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(SalesKey, SalesData))],
        ['query'],
      ),
    'getAllMonthsSorted' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(SalesKey, SalesData))],
        ['query'],
      ),
    'getMonth' : IDL.Func([SalesKey], [SalesData], ['query']),
    'saveMonth' : IDL.Func([SalesKey, SalesData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };