/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SalesKey = IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Nat });
export const Category = IDL.Record({
  'achieved' : IDL.Float64,
  'target' : IDL.Float64,
});
export const SalesData = IDL.Record({
  'value' : Category,
  'plan' : Category,
  'withoutCoin' : Category,
  'overallSale' : Category,
  'studded' : Category,
  'plain' : Category,
});

export const idlService = IDL.Service({
  'deleteUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getAllMonths' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(SalesKey, SalesData))],
      ['query'],
    ),
  'getAllMonthsSorted' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(SalesKey, SalesData))],
      ['query'],
    ),
  'getMonth' : IDL.Func([IDL.Text, SalesKey], [SalesData], ['query']),
  'isAdminUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveMonth' : IDL.Func([IDL.Text, SalesKey, SalesData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SalesKey = IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Nat });
  const Category = IDL.Record({
    'achieved' : IDL.Float64,
    'target' : IDL.Float64,
  });
  const SalesData = IDL.Record({
    'value' : Category,
    'plan' : Category,
    'withoutCoin' : Category,
    'overallSale' : Category,
    'studded' : Category,
    'plain' : Category,
  });
  
  return IDL.Service({
    'deleteUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getAllMonths' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(SalesKey, SalesData))],
        ['query'],
      ),
    'getAllMonthsSorted' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(SalesKey, SalesData))],
        ['query'],
      ),
    'getMonth' : IDL.Func([IDL.Text, SalesKey], [SalesData], ['query']),
    'isAdminUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveMonth' : IDL.Func([IDL.Text, SalesKey, SalesData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };