/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'achieved' : number, 'target' : number }
export interface SalesData {
  'value' : Category,
  'plan' : Category,
  'withoutCoin' : Category,
  'overallSale' : Category,
  'studded' : Category,
  'plain' : Category,
}
export interface SalesKey { 'month' : bigint, 'year' : bigint }
export interface _SERVICE {
  'deleteUser' : ActorMethod<[string, string], boolean>,
  'getAllMonths' : ActorMethod<[string], Array<[SalesKey, SalesData]>>,
  'getAllMonthsSorted' : ActorMethod<[string], Array<[SalesKey, SalesData]>>,
  'getMonth' : ActorMethod<[string, SalesKey], SalesData>,
  'isAdminUser' : ActorMethod<[string], boolean>,
  'listUsers' : ActorMethod<[], Array<string>>,
  'loginUser' : ActorMethod<[string, string], boolean>,
  'registerUser' : ActorMethod<[string, string], boolean>,
  'saveMonth' : ActorMethod<[string, SalesKey, SalesData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];